version: '3.4'

services:
  cardservice:
    image: ${DOCKER_REGISTRY-}cardservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "6001:6001"
     - "6000:6000"
  transactionservice:
    image: ${DOCKER_REGISTRY-}transactionservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "7001:7001"
     - "7000:7000"
